### PR TITLE
Bugfix/throughputs update

### PR DESCRIPTION
**Pull request by rhiannonlynne**

### CODE REVIEW

**Comment by danielsf** [comment]
It does not look like you pushed your changes to testMatchSED.py

**Comment by rhiannonlynne** [comment]
That is because I'm a pathetic (or bad git user?) panda and merged this branch first, then reopened for the additional changes that I found necessary later.
(see commit https://github.com/lsst/sims_photUtils/commit/6376424380f58d74a7ff244997235135b74d368e)

**Comment by rhiannonlynne** [comment]
If I was a very good git user, I might figure out how to undo the merge and put them all back in the same place.

**Comment by rhiannonlynne** [comment]
Scott addressed some problems with my previous merge and made a new branch. I've added the necessary commits from here and will just use that branch instead.

**Pull request closed without merging**
